export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const GET_ALL_TASKS_START = 'GET_ALL_TASKS_START';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_FAILURE = 'GET_ALL_TASKS_FAILURE';

export const GET_ALL_PROJECT_TASKS_START = 'GET_ALL_PROJECT_TASKS_START';
export const GET_ALL_PROJECT_TASKS_SUCCESS = 'GET_ALL_PROJECT_TASKS_SUCCESS';
export const GET_ALL_PROJECT_TASKS_FAILURE = 'GET_ALL_PROJECT_TASKS_FAILURE';

export const GET_MY_TASKS_START = 'GET_MY_TASKS_START';
export const GET_MY_TASKS_SUCCESS = 'GET_MY_TASKS_SUCCESS';
export const GET_MY_TASKS_FAILURE = 'GET_MY_TASKS_FAILURE';

export const GET_TASKS_FOR_HOME_START = 'GET_TASKS_FOR_HOME_START';
export const GET_TASKS_FOR_HOME_SUCCESS = 'GET_TASKS_FOR_HOME_SUCCESS';
export const GET_TASKS_FOR_HOME_FAILURE = 'GET_TASKS_FOR_HOME_FAILURE';

export const START_TASK_START = 'START_TASK_START';
export const START_TASK_SUCCESS = 'START_TASK_SUCCESS';
export const START_TASK_FAILURE = 'START_TASK_FAILURE';

export const EDIT_TASK_START = 'EDIT_TASK_START';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const GET_ALL_TASK_COMMENTS_START = 'GET_ALL_TASK_COMMENTS_START';
export const GET_ALL_TASK_COMMENTS_SUCCESS = 'GET_ALL_TASK_COMMENTS_SUCCESS';
export const GET_ALL_TASK_COMMENTS_FAILURE = 'GET_ALL_TASK_COMMENTS_FAILURE';

export const GET_TASK_REPLY_COMMENTS_START = 'GET_TASK_REPLY_COMMENTS_START';
export const GET_TASK_REPLY_COMMENTS_SUCCESS = 'GET_TASK_REPLY_COMMENTS_SUCCESS';
export const GET_TASK_REPLY_COMMENTS_FAILURE = 'GET_TASK_REPLY_COMMENTS_FAILURE';

export const CREATE_TASK_COMMENT_START = 'CREATE_TASK_COMMENT_START';
export const CREATE_TASK_COMMENT_SUCCESS = 'CREATE_TASK_COMMENT_SUCCESS';
export const CREATE_TASK_COMMENT_FAILURE = 'CREATE_TASK_COMMENT_FAILURE';

export const CREATE_TASK_FILE_START = 'CREATE_TASK_FILE_START';
export const CREATE_TASK_FILE_SUCCESS = 'CREATE_TASK_FILE_SUCCESS';
export const CREATE_TASK_FILE_FAILURE = 'CREATE_TASK_FILE_FAILURE';

export const GET_ALL_TASK_FILES_START = 'GET_ALL_TASK_FILES_START';
export const GET_ALL_TASK_FILES_SUCCESS = 'GET_ALL_TASK_FILES_SUCCESS';
export const GET_ALL_TASK_FILES_FAILURE = 'GET_ALL_TASK_FILES_FAILURE';

export const DELETE_TASK_FILE_START = 'DELETE_TASK_FILE_START';
export const DELETE_TASK_FILE_SUCCESS = 'DELETE_TASK_FILE_SUCCESS';
export const DELETE_TASK_FILE_FAILURE = 'DELETE_TASK_FILE_FAILURE';

// ----------------------------------------------------------------------
// AUTH ACTION TYPES
// ----------------------------------------------------------------------

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_USER_BY_ID_START = 'GET_USER_BY_ID_START';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CHANGE_USER_FULLNAME_SUCCESS = 'CHANGE_USER_FULLNAME_SUCCESS';
export const CHANGE_USER_FULLNAME_FAILURE = 'CHANGE_USER_FULLNAME_FAILURE';

export const UPDATE_PP_SUCCESS = 'UPDATE_PP_SUCCESS';
export const UPDATE_PP_FAILURE = 'UPDATE_PP_FAILURE';

// ----------------------------------------------------------------------
// TEAM ACTION TYPES
// ----------------------------------------------------------------------

export const GET_SINGLE_TEAM_SUCCESS = 'GET_SINGLE_TEAM_SUCCESS';
export const GET_SINGLE_TEAM_FAILURE = 'GET_SINGLE_TEAM_FAILURE';

export const GET_ALL_TEAMS_START = 'GET_ALL_TEAMS_START';
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS';
export const GET_ALL_TEAMS_FAILURE = 'GET_ALL_TEAMS_FAILURE';

export const GET_TEAMS_FOR_HOME_START = 'GET_TEAMS_FOR_HOME_START';
export const GET_TEAMS_FOR_HOME_SUCCESS = 'GET_TEAMS_FOR_HOME_SUCCESS';
export const GET_TEAMS_FOR_HOME_FAILURE = 'GET_TEAMS_FOR_HOME_FAILURE';

export const DELETE_TEAM_START = 'DELETE_TEAM_START';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAILURE = 'DELETE_TEAM_FAILURE';

export const GET_ALL_CREATED_TEAMS_START = 'GET_ALL_CREATED_TEAMS_START';
export const GET_ALL_CREATED_TEAMS_SUCCESS = 'GET_ALL_CREATED_TEAMS_SUCCESS';
export const GET_ALL_CREATED_TEAMS_FAILURE = 'GET_ALL_CREATED_TEAMS_FAILURE';

export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE';

export const GET_TEAM_MEMBERS_START = 'GET_TEAM_MEMBERS_START';
export const GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_FAILURE = 'GET_TEAM_MEMBERS_FAILURE';

// ----------------------------------------------------------------------
// PROJECT ACTION TYPES
// ----------------------------------------------------------------------

export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const GET_SINGLE_PROJECT_START = 'GET_SINGLE_PROJECT_START';
export const GET_SINGLE_PROJECT_SUCCESS = 'GET_SINGLE_PROJECT_SUCCESS';
export const GET_SINGLE_PROJECT_FAILURE = 'GET_SINGLE_PROJECT_FAILURE';

export const GET_ALL_PROJECTS_START = 'GET_ALL_PROJECTS_START';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_FAILURE = 'GET_ALL_PROJECTS_FAILURE';

export const GET_ALL_PROJECTS_FOR_HOME_START = 'GET_ALL_PROJECTS_FOR_HOME_START';
export const GET_ALL_PROJECTS_FOR_HOME_SUCCESS = 'GET_ALL_PROJECTS_FOR_HOME_SUCCESS';
export const GET_ALL_PROJECTS_FOR_HOME_FAILURE = 'GET_ALL_PROJECTS_FOR_HOME_FAILURE';

export const GET_PROJECTS_FOR_TEAM_START = 'GET_PROJECTS_FOR_TEAM_START';
export const GET_PROJECTS_FOR_TEAM_SUCCESS = 'GET_PROJECTS_FOR_TEAM_SUCCESS';
export const GET_PROJECTS_FOR_TEAM_FAILURE = 'GET_PROJECTS_FOR_TEAM_FAILURE';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

export const CREATE_PROJECT_FILE_START = 'CREATE_PROJECT_FILE_START';
export const CREATE_PROJECT_FILE_SUCCESS = 'CREATE_PROJECT_FILE_SUCCESS';
export const CREATE_PROJECT_FILE_FAILURE = 'CREATE_PROJECT_FILE_FAILURE';

export const GET_ALL_PROJECT_FILES_START = 'GET_ALL_PROJECT_FILES_START';
export const GET_ALL_PROJECT_FILES_SUCCESS = 'GET_ALL_PROJECT_FILES_SUCCESS';
export const GET_ALL_PROJECT_FILES_FAILURE = 'GET_ALL_PROJECT_FILES_FAILURE';

export const DELETE_PROJECT_FILE_START = 'DELETE_PROJECT_FILE_START';
export const DELETE_PROJECT_FILE_SUCCESS = 'DELETE_PROJECT_FILE_SUCCESS';
export const DELETE_PROJECT_FILE_FAILURE = 'DELETE_PROJECT_FILE_FAILURE';

export const SEND_PARENT_MESSAGE_SUCCESS = 'SEND_PARENT_MESSAGE_SUCCESS';
export const SEND_PARENT_MESSAGE_FAILURE = 'SEND_PARENT_MESSAGE_FAILURE';

export const SEND_CHILD_MESSAGE_SUCCESS = 'SEND_CHILD_MESSAGE_SUCCESS';
export const SEND_CHILD_MESSAGE_FAILURE = 'SEND_CHILD_MESSAGE_FAILURE';

export const GET_ALL_PROJECT_COMMENTS_REQUEST = 'GET_ALL_PROJECT_COMMENTS_REQUEST';
export const GET_ALL_PROJECT_COMMENTS_SUCCESS = 'GET_ALL_PROJECT_COMMENTS_SUCCESS';
export const GET_ALL_PROJECT_COMMENTS_ERROR = 'GET_ALL_PROJECT_COMMENTS_ERROR';

export const GET_PROJECT_REPLY_COMMENTS_START = 'GET_PROJECT_REPLY_COMMENTS_START';
export const GET_PROJECT_REPLY_COMMENTS_SUCCESS = 'GET_PROJECT_REPLY_COMMENTS_SUCCESS';
export const GET_PROJECT_REPLY_COMMENTS_FAILURE = 'GET_PROJECT_REPLY_COMMENTS_FAILURE';

export const GET_PROJECT_PARENT_COMMENTS_FOR_DETAIL_START = 'GET_ALL_PROJECT_COMMENTS_REQUEST';
export const GET_PROJECT_PARENT_COMMENTS_FOR_DETAIL_SUCCESS = 'GET_ALL_PROJECT_COMMENTS_SUCCESS';
export const GET_PROJECT_PARENT_COMMENTS_FOR_DETAIL_ERROR = 'GET_ALL_PROJECT_COMMENTS_ERROR';

export const GET_ALL_PROJECT_CHILD_COMMENTS_REQUEST = 'GET_ALL_PROJECT_CHILD_COMMENTS_REQUEST';
export const GET_ALL_PROJECT_CHILD_COMMENTS_SUCCESS = 'GET_ALL_PROJECT_CHILD_COMMENTS_SUCCESS';
export const GET_ALL_PROJECT_CHILD_COMMENTS_ERROR = 'GET_ALL_PROJECT_CHILD_COMMENTS_ERROR';

// ----------------------------------------------------------------------
// SPRINT ACTION TYPES
// ----------------------------------------------------------------------

export const GET_ALL_SPRINTS_START = 'GET_ALL_SPRINTS_START';
export const GET_ALL_SPRINTS_SUCCESS = 'GET_ALL_SPRINTS_SUCCESS';
export const GET_ALL_SPRINTS_FAILURE = 'GET_ALL_SPRINTS_FAILURE';

export const GET_SPRINTS_FOR_PROJECT_START = 'GET_SPRINTS_FOR_PROJECT_START';
export const GET_SPRINTS_FOR_PROJECT_SUCCESS = 'GET_SPRINTS_FOR_PROJECT_SUCCESS';
export const GET_SPRINTS_FOR_PROJECT_FAILURE = 'GET_SPRINTS_FOR_PROJECT_FAILURE';

export const GET_SPRINTS_FOR_HOME_START = 'GET_SPRINTS_FOR_HOME_START';
export const GET_SPRINTS_FOR_HOME_SUCCESS = 'GET_SPRINTS_FOR_HOME_SUCCESS';
export const GET_SPRINTS_FOR_HOME_FAILURE = 'GET_SPRINTS_FOR_HOME_FAILURE';

export const GET_SINGLE_SPRINT_START = 'GET_SINGLE_SPRINT_START';
export const GET_SINGLE_SPRINT_SUCCESS = 'GET_SINGLE_SPRINT_SUCCESS';
export const GET_SINGLE_SPRINT_FAILURE = 'GET_SINGLE_SPRINT_FAILURE';

export const CREATE_SPRINT_START = 'CREATE_SPRINT_START';
export const CREATE_SPRINT_SUCCESS = 'CREATE_SPRINT_SUCCESS';
export const CREATE_SPRINT_FAILURE = 'CREATE_SPRINT_FAILURE';

export const START_SPRINT_START = 'START_SPRINT_START';
export const START_SPRINT_SUCCESS = 'START_SPRINT_SUCCESS';
export const START_SPRINT_FAILURE = 'START_SPRINT_FAILURE';

export const FINISH_SPRINT_START = 'FINISH_SPRINT_START';
export const FINISH_SPRINT_SUCCESS = 'FINISH_SPRINT_SUCCESS';
export const FINISH_SPRINT_FAILURE = 'FINISH_SPRINT_FAILURE';

export const EDIT_SPRINT_START = 'EDIT_SPRINT_START';
export const EDIT_SPRINT_SUCCESS = 'EDIT_SPRINT_SUCCESS';
export const EDIT_SPRINT_FAILURE = 'EDIT_SPRINT_FAILURE';

export const DELETE_SPRINT_START = 'DELETE_SPRINT_START';
export const DELETE_SPRINT_SUCCESS = 'DELETE_SPRINT_SUCCESS';
export const DELETE_SPRINT_FAILURE = 'DELETE_SPRINT_FAILURE';

// ----------------------------------------------------------------------
// DAILY SCRUM MEETING ACTION TYPES
// ----------------------------------------------------------------------

export const GET_DAILY_SCRUM_MEETING_START = 'GET_DAILY_SCRUM_MEETING_START';
export const GET_DAILY_SCRUM_MEETING_SUCCESS = 'GET_DAILY_SCRUM_MEETING_SUCCESS';
export const GET_DAILY_SCRUM_MEETING_FAILURE = 'GET_DAILY_SCRUM_MEETING_FAILURE';

export const CREATE_DAILY_SCRUM_MEETING_START = 'CREATE_DAILY_SCRUM_MEETING_START';
export const CREATE_DAILY_SCRUM_MEETING_SUCCESS = 'CREATE_DAILY_SCRUM_MEETING_SUCCESS';
export const CREATE_DAILY_SCRUM_MEETING_FAILURE = 'CREATE_DAILY_SCRUM_MEETING_FAILURE';

export const DELETE_DAILY_SCRUM_MEETING_START = 'DELETE_DAILY_SCRUM_MEETING_START';
export const DELETE_DAILY_SCRUM_MEETING_SUCCESS = 'DELETE_DAILY_SCRUM_MEETING_SUCCESS';
export const DELETE_DAILY_SCRUM_MEETING_FAILURE = 'DELETE_DAILY_SCRUM_MEETING_FAILURE';

export const GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_START = 'GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_START';
export const GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_SUCCESS = 'GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_SUCCESS';
export const GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_FAILURE = 'GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_FAILURE';

export const CREATE_DAILY_SCRUM_MEETING_MESSAGE_START = 'CREATE_DAILY_SCRUM_MEETING_MESSAGE_START';
export const CREATE_DAILY_SCRUM_MEETING_MESSAGE_SUCCESS = 'CREATE_DAILY_SCRUM_MEETING_MESSAGE_SUCCESS';
export const CREATE_DAILY_SCRUM_MEETING_MESSAGE_FAILURE = 'CREATE_DAILY_SCRUM_MEETING_MESSAGE_FAILURE';

// ----------------------------------------------------------------------
// SPRINT PLANNING MEETING ACTION TYPES
// ----------------------------------------------------------------------

export const GET_ALL_SPRINT_PLANNING_MEETINGS_START = 'GET_ALL_SPRINT_PLANNING_MEETINGS_START';
export const GET_ALL_SPRINT_PLANNING_MEETINGS_SUCCESS = 'GET_ALL_SPRINT_PLANNING_MEETINGS_SUCCESS';
export const GET_ALL_SPRINT_PLANNING_MEETINGS_FAILURE = 'GET_ALL_SPRINT_PLANNING_MEETINGS_FAILURE';

export const CREATE_SPRINT_PLANNING_MEETING_START = 'CREATE_SPRINT_PLANNING_MEETING_START';
export const CREATE_SPRINT_PLANNING_MEETING_SUCCESS = 'CREATE_SPRINT_PLANNING_MEETING_SUCCESS';
export const CREATE_SPRINT_PLANNING_MEETING_FAILURE = 'CREATE_SPRINT_PLANNING_MEETING_FAILURE';

export const DELETE_SPRINT_PLANNING_MEETING_START = 'DELETE_SPRINT_PLANNING_MEETING_START';
export const DELETE_SPRINT_PLANNING_MEETING_SUCCESS = 'DELETE_SPRINT_PLANNING_MEETING_SUCCESS';
export const DELETE_SPRINT_PLANNING_MEETING_FAILURE = 'DELETE_SPRINT_PLANNING_MEETING_FAILURE';
