import {createStackNavigator} from "react-navigation-stack";
import {
    CreateProject,
    CreateProjectComment,
    ProjectAllTasks,
    ProjectCommentDetail,
    ProjectCommentList,
    ProjectCommentReply,
    ProjectDescription,
    ProjectDetail,
    ProjectFileList,
    ProjectFileUpload,
    ProjectList,
    ProjectMyTasks,
    ProjectNotes,
    ProjectSendComment,
    CreateTask,
    CreateTaskComment,
    CreateTaskFile,
    EditTask,
    ProjectTaskList,
    StartTask,
    TaskCommentDetail,
    TaskCommentList,
    TaskCommentReply,
    TaskDetail,
    TaskFileList,
    TaskList,
    CreateSprint,
    DailyScrumMeeting,
    EditSprint,
    SprintDetail,
    SprintList,
    StartSprint,
    SprintTaskList,
} from 'screens';

const ProjectNavigator = createStackNavigator(
    {
        ProjectList,
        CreateProject,
        ProjectDetail,
        ProjectDescription,
        ProjectNotes,
        ProjectMyTasks,
        CreateProjectComment,
        ProjectCommentList,
        ProjectCommentDetail,
        ProjectCommentReply,
        ProjectFileList,
        ProjectFileUpload,
        ProjectAllTasks,
        ProjectTaskList,
        TaskList,
        CreateTask,
        StartTask,
        CreateTaskFile,
        TaskDetail,
        EditTask,
        TaskFileList,
        TaskCommentList,
        CreateTaskComment,
        TaskCommentDetail,
        TaskCommentReply,
        ProjectSendComment,
        CreateSprint,
        SprintList,
        EditSprint,
        SprintDetail,
        StartSprint,
        DailyScrumMeeting,
        SprintTaskList,
    },
    {
        initialRouteName: 'ProjectList',
        headerMode: 'none',
    }
);

export default ProjectNavigator;
