export const GET_DAILY_SCRUM_MEETING_START = 'GET_DAILY_SCRUM_MEETING_START';
export const GET_DAILY_SCRUM_MEETING_SUCCESS = 'GET_DAILY_SCRUM_MEETING_SUCCESS';
export const GET_DAILY_SCRUM_MEETING_FAILURE = 'GET_DAILY_SCRUM_MEETING_FAILURE';

export const CREATE_DAILY_SCRUM_MEETING_START = 'CREATE_DAILY_SCRUM_MEETING_START';
export const CREATE_DAILY_SCRUM_MEETING_SUCCESS = 'CREATE_DAILY_SCRUM_MEETING_SUCCESS';
export const CREATE_DAILY_SCRUM_MEETING_FAILURE = 'CREATE_DAILY_SCRUM_MEETING_FAILURE';

export const START_DAILY_SCRUM_MEETING_START = 'START_DAILY_SCRUM_MEETING_START';
export const START_DAILY_SCRUM_MEETING_SUCCESS = 'START_DAILY_SCRUM_MEETING_SUCCESS';
export const START_DAILY_SCRUM_MEETING_FAILURE = 'START_DAILY_SCRUM_MEETING_FAILURE';

export const FINISH_DAILY_SCRUM_MEETING_START = 'FINISH_DAILY_SCRUM_MEETING_START';
export const FINISH_DAILY_SCRUM_MEETING_SUCCESS = 'FINISH_DAILY_SCRUM_MEETING_SUCCESS';
export const FINISH_DAILY_SCRUM_MEETING_FAILURE = 'FINISH_DAILY_SCRUM_MEETING_FAILURE';

export const DELETE_DAILY_SCRUM_MEETING_START = 'DELETE_DAILY_SCRUM_MEETING_START';
export const DELETE_DAILY_SCRUM_MEETING_SUCCESS = 'DELETE_DAILY_SCRUM_MEETING_SUCCESS';
export const DELETE_DAILY_SCRUM_MEETING_FAILURE = 'DELETE_DAILY_SCRUM_MEETING_FAILURE';

export const GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_START = 'GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_START';
export const GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_SUCCESS = 'GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_SUCCESS';
export const GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_FAILURE = 'GET_ALL_DAILY_SCRUM_MEETING_MESSAGES_FAILURE';

export const CREATE_DAILY_SCRUM_MEETING_MESSAGE_START = 'CREATE_DAILY_SCRUM_MEETING_MESSAGE_START';
export const CREATE_DAILY_SCRUM_MEETING_MESSAGE_SUCCESS = 'CREATE_DAILY_SCRUM_MEETING_MESSAGE_SUCCESS';
export const CREATE_DAILY_SCRUM_MEETING_MESSAGE_FAILURE = 'CREATE_DAILY_SCRUM_MEETING_MESSAGE_FAILURE';
