export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const EDIT_PROJECT_DESCRIPTION_REQUEST = 'EDIT_PROJECT_DESCRIPTION_REQUEST';
export const EDIT_PROJECT_DESCRIPTION_SUCCESS = 'EDIT_PROJECT_DESCRIPTION_SUCCESS';
export const EDIT_PROJECT_DESCRIPTION_FAILURE = 'EDIT_PROJECT_DESCRIPTION_FAILURE';

export const ADD_PROJECT_NOTE_REQUEST = 'ADD_PROJECT_NOTE_REQUEST';
export const ADD_PROJECT_NOTE_SUCCESS = 'ADD_PROJECT_NOTE_SUCCESS';
export const ADD_PROJECT_NOTE_FAILURE = 'ADD_PROJECT_NOTE_FAILURE';

export const EDIT_PROJECT_NOTE_REQUEST = 'EDIT_PROJECT_NOTE_REQUEST';
export const EDIT_PROJECT_NOTE_SUCCESS = 'EDIT_PROJECT_NOTE_SUCCESS';
export const EDIT_PROJECT_NOTE_FAILURE = 'EDIT_PROJECT_NOTE_FAILURE';

export const GET_SINGLE_PROJECT_START = 'GET_SINGLE_PROJECT_START';
export const GET_SINGLE_PROJECT_SUCCESS = 'GET_SINGLE_PROJECT_SUCCESS';
export const GET_SINGLE_PROJECT_FAILURE = 'GET_SINGLE_PROJECT_FAILURE';

export const GET_ALL_PROJECTS_START = 'GET_ALL_PROJECTS_START';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_FAILURE = 'GET_ALL_PROJECTS_FAILURE';

export const GET_PROJECT_DESCRIPTION_REQUEST = 'GET_PROJECT_DESCRIPTION_REQUEST';
export const GET_PROJECT_DESCRIPTION_SUCCESS = 'GET_PROJECT_DESCRIPTION_SUCCESS';
export const GET_PROJECT_DESCRIPTION_FAILURE = 'GET_PROJECT_DESCRIPTION_FAILURE';

export const GET_PROJECT_NOTES_REQUEST = 'GET_PROJECT_NOTES_REQUEST';
export const GET_PROJECT_NOTES_SUCCESS = 'GET_PROJECT_NOTES_SUCCESS';
export const GET_PROJECT_NOTES_FAILURE = 'GET_PROJECT_NOTES_FAILURE';

export const GET_ALL_PROJECTS_FOR_HOME_START = 'GET_ALL_PROJECTS_FOR_HOME_START';
export const GET_ALL_PROJECTS_FOR_HOME_SUCCESS = 'GET_ALL_PROJECTS_FOR_HOME_SUCCESS';
export const GET_ALL_PROJECTS_FOR_HOME_FAILURE = 'GET_ALL_PROJECTS_FOR_HOME_FAILURE';

export const GET_PROJECTS_FOR_TEAM_START = 'GET_PROJECTS_FOR_TEAM_START';
export const GET_PROJECTS_FOR_TEAM_SUCCESS = 'GET_PROJECTS_FOR_TEAM_SUCCESS';
export const GET_PROJECTS_FOR_TEAM_FAILURE = 'GET_PROJECTS_FOR_TEAM_FAILURE';

export const GET_PROJECTS_FOR_USER_START = 'GET_PROJECTS_FOR_USER_START';
export const GET_PROJECTS_FOR_USER_SUCCESS = 'GET_PROJECTS_FOR_USER_SUCCESS';
export const GET_PROJECTS_FOR_USER_FAILURE = 'GET_PROJECTS_FOR_USER_FAILURE';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

export const CREATE_PROJECT_FILE_START = 'CREATE_PROJECT_FILE_START';
export const CREATE_PROJECT_FILE_SUCCESS = 'CREATE_PROJECT_FILE_SUCCESS';
export const CREATE_PROJECT_FILE_FAILURE = 'CREATE_PROJECT_FILE_FAILURE';

export const GET_ALL_PROJECT_FILES_START = 'GET_ALL_PROJECT_FILES_START';
export const GET_ALL_PROJECT_FILES_SUCCESS = 'GET_ALL_PROJECT_FILES_SUCCESS';
export const GET_ALL_PROJECT_FILES_FAILURE = 'GET_ALL_PROJECT_FILES_FAILURE';

export const DELETE_PROJECT_FILE_START = 'DELETE_PROJECT_FILE_START';
export const DELETE_PROJECT_FILE_SUCCESS = 'DELETE_PROJECT_FILE_SUCCESS';
export const DELETE_PROJECT_FILE_FAILURE = 'DELETE_PROJECT_FILE_FAILURE';

export const SEND_PARENT_MESSAGE_SUCCESS = 'SEND_PARENT_MESSAGE_SUCCESS';
export const SEND_PARENT_MESSAGE_FAILURE = 'SEND_PARENT_MESSAGE_FAILURE';

export const SEND_CHILD_MESSAGE_SUCCESS = 'SEND_CHILD_MESSAGE_SUCCESS';
export const SEND_CHILD_MESSAGE_FAILURE = 'SEND_CHILD_MESSAGE_FAILURE';

export const GET_ALL_PROJECT_COMMENTS_REQUEST = 'GET_ALL_PROJECT_COMMENTS_REQUEST';
export const GET_ALL_PROJECT_COMMENTS_SUCCESS = 'GET_ALL_PROJECT_COMMENTS_SUCCESS';
export const GET_ALL_PROJECT_COMMENTS_ERROR = 'GET_ALL_PROJECT_COMMENTS_ERROR';

export const GET_PROJECT_REPLY_COMMENTS_START = 'GET_PROJECT_REPLY_COMMENTS_START';
export const GET_PROJECT_REPLY_COMMENTS_SUCCESS = 'GET_PROJECT_REPLY_COMMENTS_SUCCESS';
export const GET_PROJECT_REPLY_COMMENTS_FAILURE = 'GET_PROJECT_REPLY_COMMENTS_FAILURE';

export const GET_PROJECT_PARENT_COMMENTS_FOR_DETAIL_START = 'GET_ALL_PROJECT_COMMENTS_REQUEST';
export const GET_PROJECT_PARENT_COMMENTS_FOR_DETAIL_SUCCESS = 'GET_ALL_PROJECT_COMMENTS_SUCCESS';
export const GET_PROJECT_PARENT_COMMENTS_FOR_DETAIL_ERROR = 'GET_ALL_PROJECT_COMMENTS_ERROR';

export const GET_ALL_PROJECT_CHILD_COMMENTS_REQUEST = 'GET_ALL_PROJECT_CHILD_COMMENTS_REQUEST';
export const GET_ALL_PROJECT_CHILD_COMMENTS_SUCCESS = 'GET_ALL_PROJECT_CHILD_COMMENTS_SUCCESS';
export const GET_ALL_PROJECT_CHILD_COMMENTS_ERROR = 'GET_ALL_PROJECT_CHILD_COMMENTS_ERROR';
