export const GET_ALL_SPRINTS_START = 'GET_ALL_SPRINTS_START';
export const GET_ALL_SPRINTS_SUCCESS = 'GET_ALL_SPRINTS_SUCCESS';
export const GET_ALL_SPRINTS_FAILURE = 'GET_ALL_SPRINTS_FAILURE';

export const GET_SPRINTS_FOR_PROJECT_START = 'GET_SPRINTS_FOR_PROJECT_START';
export const GET_SPRINTS_FOR_PROJECT_SUCCESS = 'GET_SPRINTS_FOR_PROJECT_SUCCESS';
export const GET_SPRINTS_FOR_PROJECT_FAILURE = 'GET_SPRINTS_FOR_PROJECT_FAILURE';

export const GET_SPRINTS_FOR_HOME_START = 'GET_SPRINTS_FOR_HOME_START';
export const GET_SPRINTS_FOR_HOME_SUCCESS = 'GET_SPRINTS_FOR_HOME_SUCCESS';
export const GET_SPRINTS_FOR_HOME_FAILURE = 'GET_SPRINTS_FOR_HOME_FAILURE';

export const GET_SINGLE_SPRINT_START = 'GET_SINGLE_SPRINT_START';
export const GET_SINGLE_SPRINT_SUCCESS = 'GET_SINGLE_SPRINT_SUCCESS';
export const GET_SINGLE_SPRINT_FAILURE = 'GET_SINGLE_SPRINT_FAILURE';

export const CREATE_SPRINT_START = 'CREATE_SPRINT_START';
export const CREATE_SPRINT_SUCCESS = 'CREATE_SPRINT_SUCCESS';
export const CREATE_SPRINT_FAILURE = 'CREATE_SPRINT_FAILURE';

export const START_SPRINT_START = 'START_SPRINT_START';
export const START_SPRINT_SUCCESS = 'START_SPRINT_SUCCESS';
export const START_SPRINT_FAILURE = 'START_SPRINT_FAILURE';

export const FINISH_SPRINT_START = 'FINISH_SPRINT_START';
export const FINISH_SPRINT_SUCCESS = 'FINISH_SPRINT_SUCCESS';
export const FINISH_SPRINT_FAILURE = 'FINISH_SPRINT_FAILURE';

export const EDIT_SPRINT_START = 'EDIT_SPRINT_START';
export const EDIT_SPRINT_SUCCESS = 'EDIT_SPRINT_SUCCESS';
export const EDIT_SPRINT_FAILURE = 'EDIT_SPRINT_FAILURE';

export const DELETE_SPRINT_START = 'DELETE_SPRINT_START';
export const DELETE_SPRINT_SUCCESS = 'DELETE_SPRINT_SUCCESS';
export const DELETE_SPRINT_FAILURE = 'DELETE_SPRINT_FAILURE';
