export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const GET_ALL_TASKS_START = 'GET_ALL_TASKS_START';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_FAILURE = 'GET_ALL_TASKS_FAILURE';

export const GET_SINGLE_TASK_START = 'GET_SINGLE_TASK_START';
export const GET_SINGLE_TASK_SUCCESS = 'GET_SINGLE_TASK_SUCCESS';
export const GET_SINGLE_TASK_FAILURE = 'GET_SINGLE_TASK_FAILURE';

export const GET_ALL_PROJECT_TASKS_START = 'GET_ALL_PROJECT_TASKS_START';
export const GET_ALL_PROJECT_TASKS_SUCCESS = 'GET_ALL_PROJECT_TASKS_SUCCESS';
export const GET_ALL_PROJECT_TASKS_FAILURE = 'GET_ALL_PROJECT_TASKS_FAILURE';

export const GET_MY_TASKS_START = 'GET_MY_TASKS_START';
export const GET_MY_TASKS_SUCCESS = 'GET_MY_TASKS_SUCCESS';
export const GET_MY_TASKS_FAILURE = 'GET_MY_TASKS_FAILURE';

export const GET_TASKS_FOR_HOME_START = 'GET_TASKS_FOR_HOME_START';
export const GET_TASKS_FOR_HOME_SUCCESS = 'GET_TASKS_FOR_HOME_SUCCESS';
export const GET_TASKS_FOR_HOME_FAILURE = 'GET_TASKS_FOR_HOME_FAILURE';

export const GET_TASKS_FOR_USER_START = 'GET_TASKS_FOR_USER_START';
export const GET_TASKS_FOR_USER_SUCCESS = 'GET_TASKS_FOR_USER_SUCCESS';
export const GET_TASKS_FOR_USER_FAILURE = 'GET_TASKS_FOR_USER_FAILURE';

export const START_TASK_START = 'START_TASK_START';
export const START_TASK_SUCCESS = 'START_TASK_SUCCESS';
export const START_TASK_FAILURE = 'START_TASK_FAILURE';

export const EDIT_TASK_START = 'EDIT_TASK_START';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const GET_ALL_TASK_COMMENTS_START = 'GET_ALL_TASK_COMMENTS_START';
export const GET_ALL_TASK_COMMENTS_SUCCESS = 'GET_ALL_TASK_COMMENTS_SUCCESS';
export const GET_ALL_TASK_COMMENTS_FAILURE = 'GET_ALL_TASK_COMMENTS_FAILURE';

export const GET_TASK_REPLY_COMMENTS_START = 'GET_TASK_REPLY_COMMENTS_START';
export const GET_TASK_REPLY_COMMENTS_SUCCESS = 'GET_TASK_REPLY_COMMENTS_SUCCESS';
export const GET_TASK_REPLY_COMMENTS_FAILURE = 'GET_TASK_REPLY_COMMENTS_FAILURE';

export const CREATE_TASK_COMMENT_START = 'CREATE_TASK_COMMENT_START';
export const CREATE_TASK_COMMENT_SUCCESS = 'CREATE_TASK_COMMENT_SUCCESS';
export const CREATE_TASK_COMMENT_FAILURE = 'CREATE_TASK_COMMENT_FAILURE';

export const CREATE_TASK_FILE_START = 'CREATE_TASK_FILE_START';
export const CREATE_TASK_FILE_SUCCESS = 'CREATE_TASK_FILE_SUCCESS';
export const CREATE_TASK_FILE_FAILURE = 'CREATE_TASK_FILE_FAILURE';

export const GET_ALL_TASK_FILES_START = 'GET_ALL_TASK_FILES_START';
export const GET_ALL_TASK_FILES_SUCCESS = 'GET_ALL_TASK_FILES_SUCCESS';
export const GET_ALL_TASK_FILES_FAILURE = 'GET_ALL_TASK_FILES_FAILURE';

export const DELETE_TASK_FILE_START = 'DELETE_TASK_FILE_START';
export const DELETE_TASK_FILE_SUCCESS = 'DELETE_TASK_FILE_SUCCESS';
export const DELETE_TASK_FILE_FAILURE = 'DELETE_TASK_FILE_FAILURE';
