export const GET_SINGLE_TEAM_SUCCESS = 'GET_SINGLE_TEAM_SUCCESS';
export const GET_SINGLE_TEAM_FAILURE = 'GET_SINGLE_TEAM_FAILURE';

export const GET_ALL_TEAMS_START = 'GET_ALL_TEAMS_START';
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS';
export const GET_ALL_TEAMS_FAILURE = 'GET_ALL_TEAMS_FAILURE';

export const GET_TEAMS_FOR_HOME_START = 'GET_TEAMS_FOR_HOME_START';
export const GET_TEAMS_FOR_HOME_SUCCESS = 'GET_TEAMS_FOR_HOME_SUCCESS';
export const GET_TEAMS_FOR_HOME_FAILURE = 'GET_TEAMS_FOR_HOME_FAILURE';

export const DELETE_TEAM_START = 'DELETE_TEAM_START';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAILURE = 'DELETE_TEAM_FAILURE';

export const GET_ALL_CREATED_TEAMS_START = 'GET_ALL_CREATED_TEAMS_START';
export const GET_ALL_CREATED_TEAMS_SUCCESS = 'GET_ALL_CREATED_TEAMS_SUCCESS';
export const GET_ALL_CREATED_TEAMS_FAILURE = 'GET_ALL_CREATED_TEAMS_FAILURE';

export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE';

export const GET_TEAM_MEMBERS_START = 'GET_TEAM_MEMBERS_START';
export const GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_FAILURE = 'GET_TEAM_MEMBERS_FAILURE';

export const GET_TEAM_USERS_ID_START = 'GET_TEAM_USERS_ID_START';
export const GET_TEAM_USERS_ID_SUCCESS = 'GET_TEAM_USERS_ID_SUCCESS';
export const GET_TEAM_USERS_ID_FAILURE = 'GET_TEAM_USERS_ID_FAILURE';
